openapi: 3.0.0
info:
  title: Transaction Microservice
  description: API to manage transactions.
  version: 1.0.0

servers:
  - url: http://localhost:8093

paths:

  /transactions:
    post:
      tags:
        - transaction
      summary: Register a transaction
      operationId: createTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionInput'
      responses:
        201:
          description: Transaction registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        400:
          description: Invalid input
  /transactions/{id}:
    get:
      tags:
        - transaction
      summary: Find transaction by ID
      operationId: findTransactionById
      parameters:
        - in: path
          name: id
          description: ID of transaction to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        400:
          description: Invalid ID supplied
        404:
          description: Credit not found

components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          example: 1
        datetime:
          type: string
          format: date-time
        transactionType:
          type: string
          enum: [deposito, retiro, pago, consumo]
        amount:
          type: number
          format: float
          example: 10.0
        cardId:
          type: string
          example: 1
    TransactionInput:
      type: object
      properties:
        transactionType:
          type: string
          enum: [deposito, retiro, pago, consumo]
        amount:
          type: number
          format: float
          example: 10.0
        cardId:
          type: string
          example: 1

tags:
  - name: transaction
    description: Operations about transactions