openapi: 3.0.0
info:
  title: Bank Account Microservice
  description: API to manage bank accounts.
  version: 1.0.0

servers:
  - url: http://localhost:8091

paths:

  /accounts:
    get:
      tags:
        - account
      summary: Get all accounts
      operationId: getAccounts
      responses:
        200:
          description: Successful Operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    post:
      tags:
        - account
      summary: Create a new account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInput'
      responses:
        201:
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          description: Invalid input
    put:
      tags:
        - account
      summary: Update account by ID
      operationId: updateAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          description: Invalid ID supplied
        404:
          description: Account not found
  /accounts/{id}:
    get:
      tags:
        - account
      summary: Find account by ID
      operationId: findAccountById
      parameters:
        - in: path
          name: id
          description: ID of account to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          description: Invalid ID supplied
        404:
          description: Account not found
    delete:
      tags:
        - account
      summary: Delete an account by ID
      operationId: DeleteAccountById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Account not found
  /accounts/client/{id}:
    get:
      tags:
        - account
      summary: Find all accounts of a client
      operationId: getAccountsOfClient
      parameters:
        - in: path
          name: id
          description: ID of account to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        400:
          description: Invalid ID supplied
        404:
          description: Account not found

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          example: 1
        accountType:
          type: string
          enum: [ahorro, corriente, plazo_fijo]
        amount:
          type: number
          format: float
          example: 10.0
        clientId:
          type: string
    AccountInput:
      type: object
      properties:
        accountType:
          type: string
          enum: [ahorro, corriente, plazo_fijo]
        clientId:
          type: string

tags:
  - name: account
    description: Operations about accounts