server:
  port: 8091

spring:
  application:
    name: msvc-account
  data:
    mongodb:
      uri: mongodb://localhost:27017/account

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka