server:
  port: 8093

spring:
  application:
    name: msvc-transactions
  data:
    mongodb:
      uri: mongodb://localhost:27017/transactions

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
