server:
  port: 8090

spring:
  application:
    name: msvc-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/clients

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
