server:
  port: 8092

spring:
  application:
    name: msvc-credit
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka